version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger-otel-tracing-laravel
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"
      - "4318:4318"
